<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = 'mautic/mautic';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'api-platform/core' => 'v4.1.19@1dcc0da1bc56f2161ecfa863f7820e332a622d37',
  'aws/aws-crt-php' => 'v1.2.7@d71d9906c7bb63a28295447ba12e74723bd3730e',
  'aws/aws-sdk-php' => '3.374.2@67b6b6210af47319c74c5666388d71bc1bc58276',
  'barryvdh/elfinder-flysystem-driver' => 'v0.4.3@064d5b2c89ca185f3736e7e5c906d76d3632b30c',
  'beberlei/doctrineextensions' => 'v1.3.0@008f162f191584a6c37c03a803f718802ba9dd9a',
  'bjeavons/zxcvbn-php' => '1.4.2@426f664501a0747beb8f3ee17ac30c7dd6327ffa',
  'brick/math' => '0.11.0@0ad82ce168c82ba30d1c01ec86116ab52f589478',
  'composer/ca-bundle' => '1.5.12@00a2f4201641d5c53f7fc0195e6c8d9fcc321a78',
  'composer/class-map-generator' => '1.7.3@86d8208fc3c649a3a999daf1a63c25201be2990f',
  'composer/composer' => '2.9.8@39ee8baff8e97a1b657bbfcd6a236ff93a5efbb2',
  'composer/installers' => 'v2.3.0@12fb2dfe5e16183de69e784a7b84046c43d97e8e',
  'composer/metadata-minifier' => '1.0.0@c549d23829536f0d0e984aaabbf02af91f443207',
  'composer/package-versions-deprecated' => '1.11.99.1@7413f0b55a051e89485c5cb9f765fe24bb02a7b6',
  'composer/pcre' => '3.3.2@b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
  'composer/semver' => '3.4.4@198166618906cb2de69b95d7d47e5fa8aa1b2b95',
  'composer/spdx-licenses' => '1.6.0@5ecd0cb4177696f9fd48f1605dda81db3dee7889',
  'composer/xdebug-handler' => '3.0.5@6c1925561632e83d60a44492e0b344cf48ab85ef',
  'cweagans/composer-patches' => '1.7.3@e190d4466fe2b103a55467dfa83fc2fecfcaf2db',
  'doctrine/cache' => '2.2.0@1ca8f21980e770095a31456042471a57bc4c68fb',
  'doctrine/collections' => '2.6.0@7713da39d8e237f28411d6a616a3dce5e20d5de2',
  'doctrine/common' => '3.4.5@6c8fef961f67b8bc802ce3e32e3ebd1022907286',
  'doctrine/data-fixtures' => '1.8.2@6fb221da56dae2011b33d47508e3b8aeb1d91db5',
  'doctrine/dbal' => '3.7.3@ce594cbc39a4866c544f1a970d285ff0548221ad',
  'doctrine/deprecations' => '1.1.6@d4fe3e6fd9bb9e72557a19674f44d8ac7db4c6ca',
  'doctrine/doctrine-bundle' => '2.11.1@4089f1424b724786c062aea50aae5f773449b94b',
  'doctrine/doctrine-fixtures-bundle' => '3.5.1@c808a0c85c38c8ee265cc8405b456c1d2b38567d',
  'doctrine/doctrine-migrations-bundle' => '3.4.1@e858ce0f5c12b266dce7dce24834448355155da7',
  'doctrine/event-manager' => '2.1.1@dda33921b198841ca8dbad2eaa5d4d34769d18cf',
  'doctrine/inflector' => '2.1.0@6d6c96277ea252fc1304627204c3d5e6e15faa3b',
  'doctrine/instantiator' => '2.0.0@c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
  'doctrine/lexer' => '3.0.1@31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
  'doctrine/migrations' => '3.9.0@325b61e41d032f5f7d7e2d11cbefff656eadc9ab',
  'doctrine/orm' => '2.20.9@87f1ba74e04c8694ca00099f3c64706ebac0b114',
  'doctrine/persistence' => '3.4.4@5785dc79a0553ba41b0dda8a7ee792053e6186c8',
  'doctrine/sql-formatter' => '1.1.3@25a06c7bf4c6b8218f47928654252863ffc890a5',
  'egulias/email-validator' => '4.0.4@d42c8731f0624ad6bdc8d3e5e9a4524f68801cfa',
  'exercise/htmlpurifier-bundle' => '5.1@a5399a26512e66bb8ccedc3278f34258ae05eabd',
  'ezyang/htmlpurifier' => 'v4.17.0@bbc513d79acf6691fa9cf10f192c90dd2957f18c',
  'friendsofsymfony/rest-bundle' => '3.8.0@d24736896518bae817bf0de8a6b682cb6535044b',
  'gaufrette/aws-s3-adapter' => 'v0.4.0@a37143f592d5cb0ba124451439af6e6da6784d89',
  'gaufrette/extras' => 'v0.1.0@a2af9a8c53591a4c43a38249e17bcdefdcea8a23',
  'geoip2/geoip2' => 'v2.13.0@6a41d8fbd6b90052bc34dff3b4252d0f88067b23',
  'giggsey/libphonenumber-for-php' => '8.13.29@b8fa0daf0c27bb6fdb5940e0288f203be7e5cfd4',
  'giggsey/locale' => '2.5@e6d4540109a01dd2bc7334cdc842d6a6a67cf239',
  'guzzlehttp/guzzle' => '7.10.0@b51ac707cfa420b7bfd4e4d5e510ba8008e822b4',
  'guzzlehttp/oauth-subscriber' => '0.8.1@92b619b03bd21396e51c62e6bce83467d2ce8f53',
  'guzzlehttp/promises' => '2.3.0@481557b130ef3790cf82b713667b43030dc9c957',
  'guzzlehttp/psr7' => '2.9.0@7d0ed42f28e42d61352a7a79de682e5e67fec884',
  'helios-ag/fm-elfinder-bundle' => '13@4b62c623bd3e724078810ced0f87c4f84866a5fe',
  'illuminate/collections' => 'v10.48.28@48de3d6bc6aa779112ddcb608a3a96fc975d89d8',
  'illuminate/conditionable' => 'v10.48.28@3ee34ac306fafc2a6f19cd7cd68c9af389e432a5',
  'illuminate/contracts' => 'v10.48.28@f90663a69f926105a70b78060a31f3c64e2d1c74',
  'illuminate/macroable' => 'v10.48.28@dff667a46ac37b634dcf68909d9d41e94dc97c27',
  'intervention/image' => '2.7.2@04be355f8d6734c826045d02a1079ad658322dad',
  'ip2location/ip2location-php' => '7.2.5@5f637f2e95e51861b9d969aa98f4e5868074f922',
  'javer/lightsaml' => '1.9.0@b2b6129ac705539639debf94532484fdbaa4493a',
  'javer/sp-bundle' => '2.1.0@1c90c5ba9e64396c47dc1ea1c492b675f0469768',
  'javer/symfony-bridge' => '1.6.0@9d65dc277278b19ba29c7589ddb1f01d59603ed5',
  'jbroadway/urlify' => '1.2.4-stable@d0fafbaa1dc14e8039cdf5c72a932a8d1de1750e',
  'jms/metadata' => '2.8.0@7ca240dcac0c655eb15933ee55736ccd2ea0d7a6',
  'jms/serializer' => '3.32.6@b02a6c00d8335ef68c163bf7c9e39f396dc5853f',
  'jms/serializer-bundle' => '5.5.1@0538a2bae32a448fdeded53d729308816b5ad2e8',
  'joomla/filter' => '3.0.5@06c9e672d15099622dbb56c8e2a7461ce26d37f6',
  'joomla/string' => '3.0.4@0b3d33564db389e27346f7e275c694897c939434',
  'justinrainbow/json-schema' => '6.8.2@2c89ebb95ca9cedc9347f780333f7b25792dcb76',
  'kamermans/guzzle-oauth2-subscriber' => 'v1.1.1@7c311987ce7dcb6bfcd8320cc64588ad8fca075a',
  'klapaudius/oauth-server-bundle' => '5.1.3@c67a39afd881b4a36adf6df74c2873b9a3ceb0b7',
  'klapaudius/oauth2-php' => '1.8.0@99b159388a002da2ca8f791b97eed4ff68e32d54',
  'knplabs/gaufrette' => 'v0.9.0@786247eba04d4693e88a80ca9fdabb634675dcac',
  'knplabs/knp-menu' => 'v3.8.0@79d325909a1d428a93f1a0f55e90177830e283bb',
  'knplabs/knp-menu-bundle' => 'v3.4.2@6a1e3e1f4131f9a5a967e36717a1fe680c183637',
  'league/flysystem' => '3.30.0@2203e3151755d874bb2943649dae1eb8533ac93e',
  'league/flysystem-local' => '3.30.0@6691915f77c7fb69adfb87dcd550052dc184ee10',
  'league/mime-type-detection' => '1.16.0@2d6702ff215bf922936ccc1ad31007edc76451b9',
  'maennchen/zipstream-php' => '3.1.2@aeadcf5c412332eb426c0f9b4485f6accba2a99f',
  'marc-mabe/php-enum' => 'v4.7.2@bb426fcdd65c60fb3638ef741e8782508fda7eef',
  'markbaker/complex' => '3.0.2@95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
  'markbaker/matrix' => '3.0.1@728434227fe21be27ff6d86621a1b13107a2562c',
  'matomo/device-detector' => '6.5.0@e0fff2309dad83eb3cfb2564e524be715cfcf3cf',
  'matthiasmullie/minify' => '1.3.71@ae42a47d7fecc1fbb7277b2f2d84c37a33edc3b1',
  'matthiasmullie/path-converter' => '1.1.3@e7d13b2c7e2f2268e1424aaed02085518afa02d9',
  'mautic/core-lib' => '7.0.0-dev@b70e758fdb639acb280da575c03dd0653d01f8f5',
  'maxmind-db/reader' => 'v1.11.1@1e66f73ffcf25e17c7a910a1317e9720a95497c7',
  'maxmind/web-service-common' => 'v0.9.0@4dc5a3e8df38aea4ca3b1096cee3a038094e9b53',
  'monolog/monolog' => '3.10.0@b321dd6749f0bf7189444158a3ce785cc16d69b0',
  'mtdowling/jmespath.php' => '2.8.0@a2a865e05d5f420b50cc2f85bb78d565db12a6bc',
  'mustangostang/spyc' => '0.6.3@4627c838b16550b666d15aeae1e5289dd5b77da0',
  'oneup/uploader-bundle' => '5.1.0@75481fd99478f307bc673667ea6c6965fbbe42e7',
  'php-http/guzzle7-adapter' => '1.0.0@fb075a71dbfa4847cf0c2938c4e5a9c478ef8b01',
  'php-http/httplug' => '2.4.0@625ad742c360c8ac580fcc647a1541d29e257f67',
  'php-http/promise' => '1.3.0@2916a606d3b390f4e9e8e2b8dd68581508be0f07',
  'phpoffice/phpspreadsheet' => '5.7.0@9f55d3b9b7bcb1084fda8340e4b7ce4ed10cd0c8',
  'phpstan/phpdoc-parser' => '2.3.2@a004701b11273a26cd7955a61d67a7f1e525a45a',
  'predis/predis' => 'v3.0.1@34fb0a7da0330df1bab4280fcac4afdeeccc3edf',
  'psr/cache' => '3.0.0@aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
  'psr/clock' => '1.0.0@e41a24703d4560fd0acb709162f73b8adfc3aa0d',
  'psr/container' => '2.0.2@c71ecc56dfe541dbd90c5360474fbc405f8d5963',
  'psr/event-dispatcher' => '1.0.0@dbefd12671e8a14ec7f180cab83036ed26714bb0',
  'psr/http-client' => '1.0.3@bb5906edc1c324c9a05aa0873d40117941e5fa90',
  'psr/http-factory' => '1.1.0@2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
  'psr/http-message' => '1.1@cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
  'psr/link' => '2.0.1@84b159194ecfd7eaa472280213976e96415433f7',
  'psr/log' => '3.0.2@f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
  'psr/simple-cache' => '2.0.0@8707bf3cea6f710bf6ef05491234e3ab06f6432a',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'ramsey/collection' => '1.3.0@ad7475d1c9e70b190ecffc58f2d989416af339b4',
  'ramsey/uuid' => '4.7.5@5f0df49ae5ad6efb7afa69e6bfab4e5b1e080d8e',
  'react/promise' => 'v3.3.0@23444f53a813a3296c1368bb104793ce8d88f04a',
  'robrichards/xmlseclibs' => '3.1.5@03062be78178cbb5e8f605cd255dc32a14981f92',
  'seld/jsonlint' => '1.11.0@1748aaf847fc731cfad7725aec413ee46f0cc3a2',
  'seld/phar-utils' => '1.2.1@ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
  'seld/signal-handler' => '2.0.2@04a6112e883ad76c0ada8e4a9f7520bbfdb6bb98',
  'simshaun/recurr' => 'v5.0.3@7b136768d64f257065e38a804ee6d2f9af6ba6d1',
  'studio-42/elfinder' => '2.1.69@8f2c3ffafcdd52cf4515f1eec172f4eee44552ad',
  'symfony/asset' => 'v7.4.8@d2e2f014ccd6ec9fae8dbe6336a4164346a2a856',
  'symfony/cache' => 'v7.4.12@902d621e0b6ef0ebeaa133770b5c339a19328589',
  'symfony/cache-contracts' => 'v3.7.0@225e8a254166bd3442e370c6f50145465db63831',
  'symfony/clock' => 'v7.4.8@674fa3b98e21531dd040e613479f5f6fa8f32111',
  'symfony/config' => 'v7.4.10@d91b6c7cd2a8c9a9c2b8d26c8f5ed48edf99ef57',
  'symfony/console' => 'v7.4.11@ed0107e43ab452aa77ae99e005b95e56b556e075',
  'symfony/dependency-injection' => 'v7.4.10@4eb0d9dfa9d4f7c59216baf49b3ed6b1fb72293d',
  'symfony/deprecation-contracts' => 'v3.7.0@50f59d1f3ca46d41ac911f97a78626b6756af35b',
  'symfony/doctrine-bridge' => 'v7.4.9@7a87c85853f3069e3657a823c62b02952de46b0a',
  'symfony/doctrine-messenger' => 'v7.4.6@a429cd95983eaea2371ea279bed3b8a93b9ecdd3',
  'symfony/dotenv' => 'v7.4.11@82e9b1355c68ef7b96397dbd34cc75a92eebae7c',
  'symfony/error-handler' => 'v7.4.8@8dd79d8af777ee6cba2fd4d98da6ffb839f3c0fa',
  'symfony/event-dispatcher' => 'v7.4.9@e4a2e29753c7801f7a8340e066cfa788f3bc8101',
  'symfony/event-dispatcher-contracts' => 'v3.7.0@ccba7060602b7fed0b03c85bf025257f76d9ef32',
  'symfony/expression-language' => 'v7.4.8@87ff95687748f4af65e4d5a6e917d448ec52aa83',
  'symfony/filesystem' => 'v7.4.11@d721ea61b4a5fba8c5b6e7c1feda19efea144b50',
  'symfony/finder' => 'v7.4.8@e0be088d22278583a82da281886e8c3592fbf149',
  'symfony/form' => 'v7.4.9@b6c107af659106abec1771d9d7d22da528644d3a',
  'symfony/framework-bundle' => 'v7.4.11@637f5cac1ac2698a012b41610215bf366004295f',
  'symfony/http-client' => 'v7.4.9@7e941c6abf4e3bf7dca160bf0e11ef36a9f832f6',
  'symfony/http-client-contracts' => 'v3.7.0@4a2d00c37651c0bdc2b9e1c773487a8bf4edb12d',
  'symfony/http-foundation' => 'v7.4.13@bc354f47c62301e990b7874fa662326368508e2c',
  'symfony/http-kernel' => 'v7.4.12@7922b53e70d2ba2027af8bb6a59d91eb3541ea4d',
  'symfony/intl' => 'v7.4.8@7cfb7792d580dea833647420afd5f2f98df8457b',
  'symfony/lock' => 'v7.4.9@fac1ee8763f1910cb3631307d88cde64ad372614',
  'symfony/mailer' => 'v7.4.12@5cefb712a25f320579615ba9e1942abaeade7dff',
  'symfony/messenger' => 'v7.4.12@906387986caecc10b2ad2e85f715d834e5133a04',
  'symfony/mime' => 'v7.4.12@b198dd66c211c97119bcaaff7c13431dbbb5e470',
  'symfony/monolog-bridge' => 'v7.4.12@20bb2345ac7a9dd57724b6b7ada92c6d7d67b4b8',
  'symfony/monolog-bundle' => 'v3.10.0@414f951743f4aa1fd0f5bf6a0e9c16af3fe7f181',
  'symfony/options-resolver' => 'v7.4.8@2888fcdc4dc2fd5f7c7397be78631e8af12e02b4',
  'symfony/password-hasher' => 'v7.4.8@18a7d92126c95962f7efbcc9e421ba710a366847',
  'symfony/polyfill-ctype' => 'v1.37.0@141046a8f9477948ff284fa65be2095baafb94f2',
  'symfony/polyfill-intl-grapheme' => 'v1.37.0@4864388bfbd3001ce88e234fab652acd91fdc57e',
  'symfony/polyfill-intl-icu' => 'v1.37.0@3510b63d07376b04e57e27e82607d468bb134f78',
  'symfony/polyfill-intl-idn' => 'v1.38.1@dc21118016c039a66235cf93d96b435ffb282412',
  'symfony/polyfill-intl-normalizer' => 'v1.37.0@3833d7255cc303546435cb650316bff708a1c75c',
  'symfony/polyfill-mbstring' => 'v1.37.0@6a21eb99c6973357967f6ce3708cd55a6bec6315',
  'symfony/polyfill-php72' => 'v1.31.0@fa2ae56c44f03bed91a39bfc9822e31e7c5c38ce',
  'symfony/polyfill-php73' => 'v1.37.0@0f68c03565dcaaf25a890667542e8bd75fe7e5bb',
  'symfony/polyfill-php80' => 'v1.37.0@dfb55726c3a76ea3b6459fcfda1ec2d80a682411',
  'symfony/polyfill-php81' => 'v1.37.0@4a4cfc2d253c21a5ad0e53071df248ed48c6ce5c',
  'symfony/polyfill-php83' => 'v1.37.0@3600c2cb22399e25bb226e4a135ce91eeb2a6149',
  'symfony/polyfill-php84' => 'v1.37.0@88486db2c389b290bf87ff1de7ebc1e13e42bb06',
  'symfony/polyfill-php85' => 'v1.37.0@fcfa4973a9917cef23f2e38774da74a2b7d115ee',
  'symfony/process' => 'v7.4.11@d9593c9efa40499eb078b81144de42cbc28a31f0',
  'symfony/property-access' => 'v7.4.8@b7dad9dae8b8a47ef7ecc76c8569e7d8c7d90cfc',
  'symfony/property-info' => 'v7.4.8@ac5e82528b986c4f7cfccbf7764b5d2e824d6175',
  'symfony/rate-limiter' => 'v7.4.10@778c5239c7fd6bf9b886dedf3d84ddb156ddb888',
  'symfony/routing' => 'v7.4.13@3a162171bb008e5e0f15dce6581373a4c0e8390d',
  'symfony/security-bundle' => 'v7.4.12@6f6f859b437fb95028addfa21b417d25daca86d5',
  'symfony/security-core' => 'v7.4.12@efff84605474ec682c7d9c6278088811e6f3caaa',
  'symfony/security-csrf' => 'v7.4.8@16b3aa2f67d02fb0dbd013a8759bbe90daaa9c5d',
  'symfony/security-http' => 'v7.4.13@da3c28025a664e6a88e1af104a74457d99301161',
  'symfony/serializer' => 'v7.4.10@268c5aa6c4bd675eddd89348e7ecac292a843ddd',
  'symfony/service-contracts' => 'v3.7.0@d25d82433a80eba6aa0e6c24b61d7370d99e444a',
  'symfony/stopwatch' => 'v7.4.8@70a852d72fec4d51efb1f48dcd968efcaf5ccb89',
  'symfony/string' => 'v7.4.11@965f7306a43383d02c6aca1e3f3bd2f0ea5dee15',
  'symfony/translation' => 'v7.4.10@ada7578c30dd5feaa8259cff3e885069ea81ddde',
  'symfony/translation-contracts' => 'v3.7.0@0ab302977a952b42fd51475c4ebac81f8da0a95d',
  'symfony/twig-bridge' => 'v7.4.12@81663873d946531129c76c65e80b681ce99c0e89',
  'symfony/twig-bundle' => 'v7.4.8@ba1e06d7ff1ebb1d1799b6608d925f4eaba88d95',
  'symfony/type-info' => 'v7.4.9@cafeedbf157b890e94ac5b83eaed85595106d5d6',
  'symfony/validator' => 'v7.4.10@c76458623af9a3fe3b2e5b09b36453f334c2a361',
  'symfony/var-dumper' => 'v7.4.8@9510c3966f749a1d1ff0059e1eabef6cc621e7fd',
  'symfony/var-exporter' => 'v7.4.9@22e03a49c95ef054a43601cd159b222bfab1c701',
  'symfony/web-link' => 'v7.4.8@0711009963009e7d6d59149327f3ad633ee3fe25',
  'symfony/yaml' => 'v7.4.12@8b6952b56ca6417f25f7a65758cadd0ce02edc51',
  'twig/string-extra' => 'v3.21.0@4b3337544ac8f76c280def94e32b53acfaec0589',
  'twig/twig' => 'v3.27.0@04ae1bfe9463c816cf72ca0abe7eae2c77a9a9ed',
  'twilio/sdk' => '5.42.2@0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
  'voku/portable-ascii' => '2.0.1@b56450eed252f6801410d810c8e1727224ae0743',
  'voku/stop-words' => '2.0.1@8e63c0af20f800b1600783764e0ce19e53969f71',
  'wikimedia/less.php' => 'v5.5.0@f12e470d4fb4478b8af759d4c5da99707af3db10',
  'willdurand/jsonp-callback-validator' => 'v2.0.0@738c36e91d4d7e0ff0cac145f77057e0fb88526e',
  'willdurand/negotiation' => '3.1.0@68e9ea0553ef6e2ee8db5c1d98829f111e623ec2',
  'behat/gherkin' => 'v4.12.0@cc3a7e224b36373be382b53ef02ede0f1807bb58',
  'clue/ndjson-react' => 'v1.3.0@392dc165fce93b5bb5c637b67e59619223c931b0',
  'codeception/codeception' => '5.2.1@6e06224627dcd89e7d4753f44ba4df35034b6314',
  'codeception/lib-asserts' => '2.2.0@06750a60af3ebc66faab4313981accec1be4eefc',
  'codeception/lib-web' => '1.0.7@1444ccc9b1d6721f3ced8703c8f4a9041b80df93',
  'codeception/module-asserts' => '3.0.0@1b6b150b30586c3614e7e5761b31834ed7968603',
  'codeception/module-db' => '3.2.2@0ac08372c13f72c33745050e396317c8456a5f7b',
  'codeception/module-webdriver' => '4.0.3@551d214ddd57a9539acf1123d7c56ec82b1004df',
  'codeception/stub' => '4.1.4@6ce453073a0c220b254dd7f4383645615e4071c3',
  'evenement/evenement' => 'v3.0.2@0a16b0d71ab13284339abb99d9d2bd813640efbc',
  'fidry/cpu-core-counter' => '1.3.0@db9508f7b1474469d9d3c53b86f817e344732678',
  'friendsofphp/php-cs-fixer' => 'v3.94.2@7787ceff91365ba7d623ec410b8f429cdebb4f63',
  'http-interop/http-factory-guzzle' => '1.2.0@8f06e92b95405216b237521cc64c804dd44c4a81',
  'liip/functional-test-bundle' => '4.13.0@f2c43ab303fadc0658edeef224159cfd493a69be',
  'liip/test-fixtures-bundle' => '3.5.0@f385458e47026b7bf5e73efe2a96c6b74805edc5',
  'masterminds/html5' => '2.10.0@fcf91eb64359852f00d921887b219479b4f21251',
  'mautic/transifex' => '5.0.0@170ee802254ac5d9a952dc4c41e82ccce79ce0d6',
  'myclabs/deep-copy' => '1.13.4@07d290f0c47959fd5eed98c95ee5602db07e0b6a',
  'nikic/php-parser' => 'v5.7.0@dca41cd15c2ac9d055ad70dbfd011130757d1f82',
  'phar-io/manifest' => '2.0.4@54750ef60c58e43759730615a392c31c80e23176',
  'phar-io/version' => '3.2.1@4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
  'php-webdriver/webdriver' => '1.15.2@998e499b786805568deaf8cbf06f4044f05d91bf',
  'phpstan/extension-installer' => '1.4.3@85e90b3942d06b2326fba0403ec24fe912372936',
  'phpstan/phpstan' => '2.1.33@9e800e6bee7d5bd02784d4c6069b48032d16224f',
  'phpstan/phpstan-deprecation-rules' => '2.0.1@1cc1259cb91ee4cfbb5c39bca9f635f067c910b4',
  'phpstan/phpstan-doctrine' => '2.0.1@bdb6a835c5aa9725979694ae9b70591e180f4853',
  'phpstan/phpstan-phpunit' => '2.0.3@e32ac656788a5bf3dedda89e6a2cad5643bf1a18',
  'phpstan/phpstan-symfony' => '2.0.0@1ef4dce2baabd464c2dd3109d051bad94efa1e79',
  'phpunit/php-code-coverage' => '10.1.16@7e308268858ed6baedc8704a304727d20bc07c77',
  'phpunit/php-file-iterator' => '4.1.0@a95037b6d9e608ba092da1b23931e537cadc3c3c',
  'phpunit/php-invoker' => '4.0.0@f5e568ba02fa5ba0ddd0f618391d5a9ea50b06d7',
  'phpunit/php-text-template' => '3.0.1@0c7b06ff49e3d5072f057eb1fa59258bf287a748',
  'phpunit/php-timer' => '6.0.0@e2a2d67966e740530f4a3343fe2e030ffdc1161d',
  'phpunit/phpunit' => '10.5.63@33198268dad71e926626b618f3ec3966661e4d90',
  'psy/psysh' => 'v0.12.19@a4f766e5c5b6773d8399711019bb7d90875a50ee',
  'react/cache' => 'v1.2.0@d47c472b64aa5608225f47965a484b75c7817d5b',
  'react/child-process' => 'v0.6.7@970f0e71945556422ee4570ccbabaedc3cf04ad3',
  'react/dns' => 'v1.14.0@7562c05391f42701c1fccf189c8225fece1cd7c3',
  'react/event-loop' => 'v1.6.0@ba276bda6083df7e0050fd9b33f66ad7a4ac747a',
  'react/socket' => 'v1.17.0@ef5b17b81f6f60504c539313f94f2d826c5faa08',
  'react/stream' => 'v1.4.0@1e5b0acb8fe55143b5b426817155190eb6f5b18d',
  'rector/rector' => '2.2.0@3c5a641c39f2def0c93d36df118fb2e75cfc2aae',
  'sebastian/cli-parser' => '2.0.1@c34583b87e7b7a8055bf6c450c2c77ce32a24084',
  'sebastian/code-unit' => '2.0.0@a81fee9eef0b7a76af11d121767abc44c104e503',
  'sebastian/code-unit-reverse-lookup' => '3.0.0@5e3a687f7d8ae33fb362c5c0743794bbb2420a1d',
  'sebastian/comparator' => '5.0.5@55dfef806eb7dfeb6e7a6935601fef866f8ca48d',
  'sebastian/complexity' => '3.2.0@68ff824baeae169ec9f2137158ee529584553799',
  'sebastian/diff' => '5.1.1@c41e007b4b62af48218231d6c2275e4c9b975b2e',
  'sebastian/environment' => '6.1.0@8074dbcd93529b357029f5cc5058fd3e43666984',
  'sebastian/exporter' => '5.1.4@0735b90f4da94969541dac1da743446e276defa6',
  'sebastian/global-state' => '6.0.2@987bafff24ecc4c9ac418cab1145b96dd6e9cbd9',
  'sebastian/lines-of-code' => '2.0.2@856e7f6a75a84e339195d48c556f23be2ebf75d0',
  'sebastian/object-enumerator' => '5.0.0@202d0e344a580d7f7d04b3fafce6933e59dae906',
  'sebastian/object-reflector' => '3.0.0@24ed13d98130f0e7122df55d06c5c4942a577957',
  'sebastian/recursion-context' => '5.0.1@47e34210757a2f37a97dcd207d032e1b01e64c7a',
  'sebastian/type' => '4.0.0@462699a16464c3944eefc02ebdd77882bd3925bf',
  'sebastian/version' => '4.0.1@c51fa83a5d8f43f1402e3f32a005e6262244ef17',
  'symfony/browser-kit' => 'v7.4.8@41850d8f8ddef9a9cd7314fa9f4902cf48885521',
  'symfony/css-selector' => 'v7.4.9@b75663ed96cf4756e28e3105476f220f92886cc4',
  'symfony/dom-crawler' => 'v7.4.12@b59b59122690976550fd142c23fab62c84738db6',
  'symfony/maker-bundle' => 'v1.67.0@6ce8b313845f16bcf385ee3cb31d8b24e30d5516',
  'symfony/phpunit-bridge' => 'v7.4.8@140bbbe1cd1c21a084494ccddeee33f3c3381d7d',
  'symfony/web-profiler-bundle' => 'v7.4.12@558fe81a383302318d9b92f7661deb731153c86e',
  'symplify/easy-coding-standard' => '12.0.13@d15707b14d50b7cb6d656f7a7a5e5b9a17099b3c',
  'theseer/tokenizer' => '1.3.1@b7489ce515e168639d17feec34b8847c326b0b3c',
  'mautic/grapes-js-builder-bundle' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-clearbit' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-cloudstorage' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-crm' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-emailmarketing' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-focus' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-fullcontact' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-gmail' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-outlook' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-social' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-zapier' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/plugin-tagmanager' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-aurora' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-blank' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-brienz' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-cards' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-confirmme' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-fresh-center' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-fresh-fixed' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-fresh-left' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-fresh-wide' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-goldstar' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-neopolitan' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-oxygen' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-paprika' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-skyline' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-sparse' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-sunday' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-vibrant' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-1-2-1-2-column' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-1-2-1-column' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-1-2-column' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-1-3-1-3-column' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-1-3-column' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-attract' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-connect-through-content' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-creative' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-educate' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-gallery' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-make-announcement' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-showcase' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-simple-text' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-survey' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-trulypersonal' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-welcome' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-mono' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-blend' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-capture' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-chord' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-formscape' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-reachout' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/theme-multi-step' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
  'mautic/mautic' => '7.x-dev@4f3d7cc3fef0a9c00fdb7dabbf37fb058363129f',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!class_exists(InstalledVersions::class, false) || !InstalledVersions::getRawData()) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (class_exists(InstalledVersions::class, false) && InstalledVersions::getRawData()) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
